### PR TITLE
Four small fixes, see the commits

### PR DESCRIPTION
**Pull request by emiljs**

### CODE REVIEW

**Comment by SolariusScorch** [comment]
The Roboturret Minigun is definitely correct as it is now. It's done like this so it could fire with reactions, which is not possible with auto shots.
Some other points I need to confirm with devs.

**Comment by SolariusScorch** [comment]
Thanks, fixed manually (except for the roboturret minigun attack - works as intended).

**Comment by emiljs** [comment]
Good point about the reaction fire. If you still want them to be have spray waypoints you could add an auto firemode

**Comment by SolariusScorch** [comment]
Yeah, we could do that, but I wanted to keep the drones somewhat "less smart".

**Pull request closed without merging**
