### PR TITLE
Minor item fixes

### PR DESCRIPTION
**Pull request by emiljs**

### CODE REVIEW

**Comment by SolariusScorch** [comment]
Good point about the hand, but the robot saw should be a "ranged" weapon, for wacky reasons.

What's the problem with Centurion melee? I can't see a fix.

**Comment by emiljs** [comment]
Sorry, I wrote centurion in the commit message, this is about STR_MAGMA_CHAINSAWBOT_WEAPON

It seems to have battletype firearm by mistake, I can't get them to hit me when testing.
Changing the battletype to melee fixed that.

Then you need to change some of the related sounds/animation for them to trigger on melee attacks:
fireSound to meleeSound
hitSound to meleeHitSound
hitAnimation to meleeAnimation
and delete bulletsprite since it won't be used

**Comment by emiljs** [comment]
But I'll try to make it work as a ranged weapon

**Comment by SolariusScorch** [comment]
I understand now.
Sorry for the bother, but could you please make another pull request for the STR_MAGMA_CHAINSAWBOT_WEAPON?

**Comment by emiljs** [comment]
https://github.com/SolariusScorch/XComFiles/pull/141 was the fix for STR_MAGMA_CHAINSAWBOT_WEAPON

**Pull request closed without merging**
