### PR TITLE
Validator fixes

### PR DESCRIPTION
**Pull request by emiljs**
Hi,

I decided to write a validator for openxcom ruleset files. It's not quite finished, but here are some of it's findings.

### CODE REVIEW

**Comment by FinnikXCF** [comment]
ruleset validator is a great thing. im using one made by SupSuper for VS Code all the time https://github.com/OpenXcom/vscode-ruleset
maybe you could collaborate? id love to see some high-level logic checks, like missing strings

**Comment by emiljs** [comment]
Yes, exactly, it's the high level logic I want to check. I'll take a look if some of it can be added to the VSCode-plugin, though I don't think all of it can...

**Comment by SolariusScorch** [comment]
Many thanks for all the reports. It was invaluable!
I fixed things by hand, as there were several cases where some of the "bugs" were intentional (for example, non-existing research topics whose role was to block the item), so I will close this commit.
Thank you again, you'll be credited :)

**Comment by emiljs** [comment]
Happy to help! Though it seems you only partially included some of the fixes:
- battle sound 834 is still referenced once. 
- STR_ALERT_NATASHA_MOROZOVA and STR_CRAFT_WEAPONS were not changed in en-US.yml

Here are the remaining bits: 
https://github.com/SolariusScorch/XComFiles/pull/81

**Pull request closed without merging**
