### PR TITLE
Misspelled items

### PR DESCRIPTION
**Pull request by emiljs**

### CODE REVIEW

**Comment by Joao-Victor-Bonfim** [comment]
Did you refactor these recursively? Because if you didn't, then problems will emerge.

**Comment by emiljs** [comment]
Not entirely sure what you mean. STR_PAINKILLERS and STR_STR_DESERT_EAGLE are just not defined anywhere, while STR_PAINKILLER and STR_DESERT_EAGLE are.

**Comment by SolariusScorch** [comment]
Ah, right... these two I just missed. Sorry! -_-  
            
          
     
      
       
        Dnia 18 kwietnia 2020 12:54 Emil J. Schroeder &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 Not entirely sure what you mean. STR_PAINKILLERS and STR_STR_DESERT_EAGLE are just not defined anywhere, while STR_PAINKILLER and STR_DESERT_EAGLE are.

**Comment by SolariusScorch** [comment]
Wait... This is a different commit than I though. Never mind.
Thank you for spotting it!

**Comment by Joao-Victor-Bonfim** [comment]
> 
> 
> Not entirely sure what you mean. STR_PAINKILLERS and STR_STR_DESERT_EAGLE are just not defined anywhere, while STR_PAINKILLER and STR_DESERT_EAGLE are.

I meant: Did you do the changes everywhere else where those could be found?

**Comment by SolariusScorch** [comment]
Hopefully :)

**Pull request merged**
